name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_REGION: eu-west-1 

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install tools
      run: dotnet tool install --global Amazon.Lambda.Tools
      
    - name: Deploy
      run: dotnet lambda deploy-serverless --s3-bucket "ae-temp" --project-location "src/Ae.Blog/Ae.Blog.csproj" --msbuild-parameters "/p:PublishReadyToRun=true --self-contained false"
